# Generated by Django 4.2.7 on 2026-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('EVENT_CANCELLED', 'Event Cancelled'), ('SEAT_RESERVED', 'Seat Reserved'), ('WELCOME', 'Welcome')], max_length=32)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['type', 'status'], name='notificatio_type_c83c59_idx')],
            },
        ),
    ]
